name: remote ssh command
on:
  push:
    branches:
      - main
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.170.31
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd shorturl
            git pull
            docker compose up -d --build app
